/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClientesContactIdRouteImport } from './routes/_authenticated/clientes.$contactId'
import { Route as AuthenticatedConfiguracoesWhatsappRouteImport } from './routes/_authenticated/configuracoes.whatsapp'
import { Route as ApiPublicHooksAiTickRouteImport } from './routes/api.public.hooks.ai-tick'
import { Route as ApiPublicHooksFollowupTickRouteImport } from './routes/api.public.hooks.followup-tick'
import { Route as ApiPublicWhatsappConnectionIdRouteImport } from './routes/api.public.whatsapp.$connectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesContactIdRoute =
  AuthenticatedClientesContactIdRouteImport.update({
    id: '/clientes/$contactId',
    path: '/clientes/$contactId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesWhatsappRoute =
  AuthenticatedConfiguracoesWhatsappRouteImport.update({
    id: '/configuracoes/whatsapp',
    path: '/configuracoes/whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksAiTickRoute = ApiPublicHooksAiTickRouteImport.update({
  id: '/api/public/hooks/ai-tick',
  path: '/api/public/hooks/ai-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksFollowupTickRoute =
  ApiPublicHooksFollowupTickRouteImport.update({
    id: '/api/public/hooks/followup-tick',
    path: '/api/public/hooks/followup-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappConnectionIdRoute =
  ApiPublicWhatsappConnectionIdRouteImport.update({
    id: '/api/public/whatsapp/$connectionId',
    path: '/api/public/whatsapp/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/clientes/$contactId': typeof AuthenticatedClientesContactIdRoute
  '/configuracoes/whatsapp': typeof AuthenticatedConfiguracoesWhatsappRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/api/public/hooks/ai-tick': typeof ApiPublicHooksAiTickRoute
  '/api/public/hooks/followup-tick': typeof ApiPublicHooksFollowupTickRoute
  '/api/public/whatsapp/$connectionId': typeof ApiPublicWhatsappConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/clientes/$contactId': typeof AuthenticatedClientesContactIdRoute
  '/configuracoes/whatsapp': typeof AuthenticatedConfiguracoesWhatsappRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/api/public/hooks/ai-tick': typeof ApiPublicHooksAiTickRoute
  '/api/public/hooks/followup-tick': typeof ApiPublicHooksFollowupTickRoute
  '/api/public/whatsapp/$connectionId': typeof ApiPublicWhatsappConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/clientes/$contactId': typeof AuthenticatedClientesContactIdRoute
  '/_authenticated/configuracoes/whatsapp': typeof AuthenticatedConfiguracoesWhatsappRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/api/public/hooks/ai-tick': typeof ApiPublicHooksAiTickRoute
  '/api/public/hooks/followup-tick': typeof ApiPublicHooksFollowupTickRoute
  '/api/public/whatsapp/$connectionId': typeof ApiPublicWhatsappConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conversas'
    | '/dashboard'
    | '/followups'
    | '/pipeline'
    | '/clientes/$contactId'
    | '/configuracoes/whatsapp'
    | '/clientes/'
    | '/api/public/hooks/ai-tick'
    | '/api/public/hooks/followup-tick'
    | '/api/public/whatsapp/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conversas'
    | '/dashboard'
    | '/followups'
    | '/pipeline'
    | '/clientes/$contactId'
    | '/configuracoes/whatsapp'
    | '/clientes'
    | '/api/public/hooks/ai-tick'
    | '/api/public/hooks/followup-tick'
    | '/api/public/whatsapp/$connectionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/conversas'
    | '/_authenticated/dashboard'
    | '/_authenticated/followups'
    | '/_authenticated/pipeline'
    | '/_authenticated/clientes/$contactId'
    | '/_authenticated/configuracoes/whatsapp'
    | '/_authenticated/clientes/'
    | '/api/public/hooks/ai-tick'
    | '/api/public/hooks/followup-tick'
    | '/api/public/whatsapp/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAiTickRoute: typeof ApiPublicHooksAiTickRoute
  ApiPublicHooksFollowupTickRoute: typeof ApiPublicHooksFollowupTickRoute
  ApiPublicWhatsappConnectionIdRoute: typeof ApiPublicWhatsappConnectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$contactId': {
      id: '/_authenticated/clientes/$contactId'
      path: '/clientes/$contactId'
      fullPath: '/clientes/$contactId'
      preLoaderRoute: typeof AuthenticatedClientesContactIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/whatsapp': {
      id: '/_authenticated/configuracoes/whatsapp'
      path: '/configuracoes/whatsapp'
      fullPath: '/configuracoes/whatsapp'
      preLoaderRoute: typeof AuthenticatedConfiguracoesWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/ai-tick': {
      id: '/api/public/hooks/ai-tick'
      path: '/api/public/hooks/ai-tick'
      fullPath: '/api/public/hooks/ai-tick'
      preLoaderRoute: typeof ApiPublicHooksAiTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/followup-tick': {
      id: '/api/public/hooks/followup-tick'
      path: '/api/public/hooks/followup-tick'
      fullPath: '/api/public/hooks/followup-tick'
      preLoaderRoute: typeof ApiPublicHooksFollowupTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/$connectionId': {
      id: '/api/public/whatsapp/$connectionId'
      path: '/api/public/whatsapp/$connectionId'
      fullPath: '/api/public/whatsapp/$connectionId'
      preLoaderRoute: typeof ApiPublicWhatsappConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedClientesContactIdRoute: typeof AuthenticatedClientesContactIdRoute
  AuthenticatedConfiguracoesWhatsappRoute: typeof AuthenticatedConfiguracoesWhatsappRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedClientesContactIdRoute: AuthenticatedClientesContactIdRoute,
  AuthenticatedConfiguracoesWhatsappRoute:
    AuthenticatedConfiguracoesWhatsappRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAiTickRoute: ApiPublicHooksAiTickRoute,
  ApiPublicHooksFollowupTickRoute: ApiPublicHooksFollowupTickRoute,
  ApiPublicWhatsappConnectionIdRoute: ApiPublicWhatsappConnectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
